apiVersion: v1
kind: Service
metadata:
  labels:
    app: solar-system
    app.kubernetes.io/instance: solar
  name: solar-system
  namespace: solar
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: solar-system
status:
  loadBalancer: {}
